export interface AttachmentMeta { id: string; name: string; type: string; size: number; createdAt: string; }
export interface Note {
  [metadata: string]: unknown; id: string; content: string; createdAt: string; updatedAt: string;
  deletedAt: string | null; isPinned: boolean; isFavorite: boolean; folder: string; tags: string[]; attachments: AttachmentMeta[];
}
export const STORAGE_KEY='classic-pocket-notes:v1'; export const DAY_MS=86400000; export const RETENTION_MS=30*DAY_MS;
export function getTitle(content:string){return content.split(/\r?\n/).find(l=>l.trim())?.trim()||'New Note'}
export function getPreview(content:string){return content.split(/\r?\n/).filter(l=>l.trim()).slice(1).join(' ').trim()}
export function sortNotes(notes:Note[]){return [...notes].sort((a,b)=>Number(b.isPinned)-Number(a.isPinned)||Number(b.isFavorite)-Number(a.isFavorite)||Date.parse(b.updatedAt)-Date.parse(a.updatedAt))}
export function isExpired(note:Note,now=Date.now()){return note.deletedAt!==null&&now-Date.parse(note.deletedAt)>=RETENTION_MS}
export function remainingDays(note:Note,now=Date.now()){if(!note.deletedAt)return 0;return Math.max(0,Math.min(30,Math.ceil((Date.parse(note.deletedAt)+RETENTION_MS-now)/DAY_MS)))}
export function remainingLabel(note:Note,now=Date.now()){const d=remainingDays(note,now);return `${d} ${d===1?'day':'days'} remaining`}
export function purgeExpired(notes:Note[],now=Date.now()){const kept=notes.filter(n=>!isExpired(n,now));return kept.length===notes.length?notes:kept}
export function activeNotes(notes:Note[],query='',folder='',tag='',favorite=false){const q=query.trim().toLowerCase(),t=tag.trim().toLowerCase();return sortNotes(notes.filter(n=>n.deletedAt===null&&(!folder||n.folder===folder)&&(!t||n.tags.some(x=>x.toLowerCase()===t))&&(!favorite||n.isFavorite)&&(!q||getTitle(n.content).toLowerCase().includes(q)||n.content.toLowerCase().includes(q)||n.folder.toLowerCase().includes(q)||n.tags.some(x=>x.toLowerCase().includes(q))))))}
export function deletedNotes(notes:Note[],now=Date.now()){return notes.filter(n=>n.deletedAt!==null&&!isExpired(n,now)).sort((a,b)=>Date.parse(b.deletedAt!)-Date.parse(a.deletedAt!))}
export type NoteAction={type:'create';note:Note}|{type:'edit';id:string;content:string}|{type:'metadata';id:string;folder:string;tags:string[];isFavorite:boolean}|{type:'pin'|'delete'|'recover'|'destroy';id:string};
export function applyNoteAction(notes:Note[],action:NoteAction,now=Date.now()){const current=purgeExpired(notes,now);if(action.type==='create')return current.some(n=>n.id===action.note.id)?current:[action.note,...current];const note=current.find(n=>n.id===action.id);if(!note)return current;if(action.type==='destroy')return note.deletedAt!==null?current.filter(n=>n.id!==note.id):current;if(action.type==='recover'){if(note.deletedAt===null)return current;return current.map(n=>n.id===note.id?{...note,deletedAt:null}:n)}if(note.deletedAt!==null)return current;let updated:Note;if(action.type==='edit'){if(note.content===action.content)return current;updated={...note,content:action.content,updatedAt:new Date(now).toISOString()}}else if(action.type==='metadata')updated={...note,folder:action.folder.trim(),tags:[...new Set(action.tags.map(t=>t.trim()).filter(Boolean))],isFavorite:action.isFavorite};else if(action.type==='pin')updated={...note,isPinned:!note.isPinned};else updated={...note,deletedAt:new Date(now).toISOString()};return current.map(n=>n.id===note.id?updated:n)}
export function decodeNotes(raw:string|null):Note[]{if(raw===null)return[];const data:unknown=JSON.parse(raw);if(!data||typeof data!=='object'||!('version'in data)||!([1,2,3] as unknown[]).includes(data.version)||!('notes'in data)||!Array.isArray(data.notes))throw new Error('Unrecognized saved notes.');const ids=new Set<string>();return sortNotes(data.notes.map((v:unknown)=>{if(!v||typeof v!=='object')throw new Error('Invalid note.');const n=v as Record<string,unknown>;if(typeof n.id!=='string'||!n.id||ids.has(n.id)||typeof n.content!=='string'||typeof n.createdAt!=='string'||!Number.isFinite(Date.parse(n.createdAt))||typeof n.updatedAt!=='string'||!Number.isFinite(Date.parse(n.updatedAt))||(n.deletedAt!=null&&(typeof n.deletedAt!=='string'||!Number.isFinite(Date.parse(n.deletedAt))))||(n.isPinned!==undefined&&typeof n.isPinned!=='boolean')||(n.isFavorite!==undefined&&typeof n.isFavorite!=='boolean')||(n.folder!==undefined&&typeof n.folder!=='string')||(n.tags!==undefined&&(!Array.isArray(n.tags)||n.tags.some(t=>typeof t!=='string'))) )throw new Error('Invalid note.');ids.add(n.id);return {...n,id:n.id,content:n.content,createdAt:n.createdAt,updatedAt:n.updatedAt,deletedAt:(n.deletedAt as string|null|undefined)??null,isPinned:(n.isPinned as boolean|undefined)??false,isFavorite:(n.isFavorite as boolean|undefined)??false,folder:(n.folder as string|undefined)??'',tags:(n.tags as string[]|undefined)??[],attachments:Array.isArray(n.attachments)?n.attachments as AttachmentMeta[]:[]})}))}
export function encodeNotes(notes:Note[]){return JSON.stringify({version:3,notes})}
export function formatListDate(iso:string){const d=new Date(iso),n=new Date();if(d.toDateString()===n.toDateString())return new Intl.DateTimeFormat('en',{hour:'numeric',minute:'2-digit'}).format(d);const y=new Date(n);y.setDate(y.getDate()-1);if(d.toDateString()===y.toDateString())return'Yesterday';return new Intl.DateTimeFormat('en',{month:'short',day:'numeric',...(d.getFullYear()!==n.getFullYear()?{year:'numeric' as const}:{})}).format(d)}
export function formatNoteDate(iso:string){return new Intl.DateTimeFormat('en',{month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(iso))}
