import{useEffect,useMemo,useRef,useState}from'react';import{flushSync}from'react-dom';import{CopyNoteSheet}from'./components/CopyNoteSheet';import{DeleteConfirmation}from'./components/DeleteConfirmation';import{useNotes}from'./hooks/useNotes';import{NoteEditor}from'./screens/NoteEditor';import{NotesList}from'./screens/NotesList';import{RecentlyDeleted}from'./screens/RecentlyDeleted';import{activeNotes,type Note}from'./utils/notes';import{shareNote}from'./utils/sharing';import{saveAttachment}from'./utils/attachments';import{downloadBlob,exportJson,exportMarkdown,importJson}from'./utils/exportImport';

type ListScreen='list'|'deleted';
export default function App(){
 const{notes,active,deleted,now,createNote,updateNote,updateMetadata,updateAttachments,importNotes,deleteNote,recoverNote,permanentlyDeleteNote,togglePin,storageError,storageBlocked,retrySave}=useNotes();
 const[activeId,setActiveId]=useState<string|null>(null),[screen,setScreen]=useState<ListScreen|'editor'>('list'),[editorSource,setEditorSource]=useState<ListScreen>('list'),[editing,setEditing]=useState(false),[query,setQuery]=useState(''),[folder,setFolder]=useState(''),[tag,setTag]=useState(''),[favorite,setFavorite]=useState(false),[confirmation,setConfirmation]=useState<'move'|'permanent'|null>(null),[copyOpen,setCopyOpen]=useState(false),[sharing,setSharing]=useState(false),[feedback,setFeedback]=useState('');
 const shareRequest=useRef(0),editor=useRef<HTMLTextAreaElement>(null),editorHeading=useRef<HTMLHeadingElement>(null),listHeading=useRef<HTMLHeadingElement>(null),deletedHeading=useRef<HTMLHeadingElement>(null);
 const activeNote=notes.find(n=>n.id===activeId)??null;const results=useMemo(()=>activeNotes(active,query,folder,tag,favorite),[active,query,folder,tag,favorite]);const editorNotes=activeNote?.deletedAt!=null?deleted:active;
 const folders=useMemo(()=>[...new Set(active.map(n=>n.folder).filter(Boolean))].sort(),[active]);const tags=useMemo(()=>[...new Set(active.flatMap(n=>n.tags))].sort(),[active]);
 useEffect(()=>{const v=window.visualViewport;const resize=()=>{if(v&&v.scale===1){document.documentElement.style.setProperty('--viewport-height',v.height+'px');document.documentElement.style.setProperty('--viewport-top',v.offsetTop+'px')}};resize();v?.addEventListener('resize',resize);v?.addEventListener('scroll',resize);return()=>{v?.removeEventListener('resize',resize);v?.removeEventListener('scroll',resize)}},[]);
 useEffect(()=>{if(!feedback)return;const t=window.setTimeout(()=>setFeedback(''),2200);return()=>clearTimeout(t)},[feedback]);
 useEffect(()=>{if(screen!=='editor'||activeNote)return;setScreen(editorSource);setEditing(false);setConfirmation(null);setCopyOpen(false);shareRequest.current++;setSharing(false);const f=requestAnimationFrame(()=>{(editorSource==='deleted'?deletedHeading:listHeading).current?.focus({preventScroll:true})});return()=>cancelAnimationFrame(f)},[screen,activeNote,editorSource]);
 function resetSharing(){shareRequest.current++;setSharing(false);setCopyOpen(false);setFeedback('')}
 function newNote(){let created:Note|null=null;flushSync(()=>{created=createNote();if(created){resetSharing();setActiveId(created.id);setEditorSource('list');setScreen('editor');setEditing(true);setQuery('')}});if(created){editor.current?.focus({preventScroll:true});editor.current?.setSelectionRange(0,0)}}
 function openNote(note:Note){flushSync(()=>{resetSharing();setActiveId(note.id);setEditorSource(note.deletedAt!==null?'deleted':'list');setScreen('editor');setEditing(false)});editor.current?.scrollTo(0,0);editorHeading.current?.focus({preventScroll:true})}
 function showList(target:ListScreen='list'){editor.current?.blur();flushSync(()=>{resetSharing();setScreen(target);setEditing(false)});(target==='deleted'?deletedHeading:listHeading).current?.focus({preventScroll:true})}
 function finishEditing(){editor.current?.blur();setEditing(false);editorHeading.current?.focus({preventScroll:true})}
 function removeNote(){if(!activeNote||storageBlocked)return;const id=activeNote.id,permanent=confirmation==='permanent';setConfirmation(null);showList(permanent?'deleted':'list');permanent?permanentlyDeleteNote(id):deleteNote(id)}
 function recover(){if(!activeNote||storageBlocked)return;const id=activeNote.id;setQuery('');showList('list');recoverNote(id)}
 async function share(){if(!activeNote||activeNote.deletedAt!==null||sharing)return;const request=++shareRequest.current;setSharing(true);const result=await shareNote(activeNote.content,navigator);if(shareRequest.current!==request)return;setSharing(false);if(result==='copy')setCopyOpen(true)}
 async function attach(file:File){if(!activeNote||storageBlocked)return;try{const meta=await saveAttachment(activeNote.id,file);const fresh=notes.find(n=>n.id===activeNote.id);if(fresh)updateAttachments(fresh.id,[...fresh.attachments,meta]);setFeedback('Attached')}catch{setFeedback('Attachment failed')}}
 function importFile(file:File){void importJson(file).then(imported=>{importNotes(imported);setFeedback('Imported')} ).catch(()=>setFeedback('Import failed'))}
 return <div className="desktop-surface"><main className="notes-app" aria-label="Pocket Notes" onKeyDown={e=>{if(e.key==='Escape'&&!confirmation&&!copyOpen){if(screen==='editor'){e.preventDefault();showList(editorSource)}else if(screen==='deleted'){e.preventDefault();showList()}}}}>
 {storageError&&<div className="storage-warning" role="alert"><span>{storageError}</span><button type="button" onClick={retrySave}>Retry</button></div>}
 <div className={'screen-stack screen-stack--'+screen+' editor-source--'+editorSource}>
 <section className="screen screen--list" aria-label="Notes list" aria-hidden={screen!=='list'} inert={screen!=='list'}><NotesList notes={results} total={active.length} deletedCount={deleted.length} query={query} onQueryChange={setQuery} folder={folder} onFolderChange={setFolder} tag={tag} onTagChange={setTag} favorite={favorite} onFavoriteChange={setFavorite} folders={folders} tags={tags} onCreate={newNote} onOpen={openNote} onDeleted={()=>showList('deleted')} blocked={storageBlocked} onExportJson={()=>downloadBlob(exportJson(notes),'pocket-notes.json')} onExportMarkdown={()=>downloadBlob(exportMarkdown(notes),'pocket-notes.md')} onImport={importFile} headingRef={listHeading}/></section>
 <section className="screen screen--deleted" aria-label="Recently Deleted" aria-hidden={screen!=='deleted'} inert={screen!=='deleted'}><RecentlyDeleted notes={deleted} now={now} onBack={()=>showList()} onOpen={openNote} headingRef={deletedHeading}/></section>
 <section className="screen screen--editor" aria-label="Note editor" aria-hidden={screen!=='editor'} inert={screen!=='editor'}><NoteEditor note={activeNote} editorRef={editor} headingRef={editorHeading} editing={editing} onEditing={setEditing} onChange={(id,c)=>updateNote(id,c)} onBack={()=>showList(editorSource)} onDone={finishEditing} onCreate={newNote} onDelete={()=>{editor.current?.blur();setConfirmation(activeNote?.deletedAt!=null?'permanent':'move')}} onRecover={recover} onPin={()=>activeNote&&togglePin(activeNote.id)} onFavorite={()=>activeNote&&updateMetadata(activeNote.id,activeNote.folder,activeNote.tags,!activeNote.isFavorite)} onMetadata={(f,t)=>activeNote&&updateMetadata(activeNote.id,f,t,activeNote.isFavorite)} onShare={()=>void share()} onAttach={attach} sharing={sharing} feedback={feedback} blocked={storageBlocked} now={now} count={editorNotes.length} position={editorNotes.findIndex(n=>n.id===activeId)+1}/></section>
 </div><DeleteConfirmation open={confirmation!==null} permanent={confirmation==='permanent'} onCancel={()=>setConfirmation(null)} onDelete={removeNote}/><CopyNoteSheet open={copyOpen} content={activeNote?.content??''} onCancel={()=>setCopyOpen(false)} onCopied={()=>{setCopyOpen(false);setFeedback('Copied')}}/></main></div>
}